EMP-2850 Introducing the Image Helper script
platform9/support-locker pull request #60
Opened 2024-11-28 14:18 UTC by sharma-tapas

1. Script Setup and Error Handling:
    - Uses set -eu for strict error handling
    - Adds set -o pipefail for bash
    - Sets a detailed debug prompt with source file and line number

2. Image Management:
    - Defines a list of container images from various registries (Kubernetes, Docker, Quay)
    - Supports pulling, pushing, and managing these images
 
3. Logging Functions:
    - Implements color-coded logging with debug(), info(), warn(), and fail() functions
    - Uses tput for terminal color control

4. Key Functions:
    - pull_images(): Pulls all defined container images
    - push_images_registry(): Pushes images to a specified registry
    - import_secrets(): Creates a Kubernetes secret from container registry authentication

5. CLI Interface:
    - Supports commands: pull, push, import-secrets
    - Offers dry-run mode with -n/--dry-run
    - Provides verbose output with -v
    - Includes usage help with -h/--help

6. Flexible Container Runtime Support:
    - Detects and uses appropriate authentication files

7. Zsh Compatibility Additions:
     - Added shell detection for zsh and bash
    - Used setopt for zsh-specific settings to match sh/bash behavior
    - Replaced $@ with $* for better cross-shell compatibility
    - Used "$*" and "$@" with quotes to handle arguments correctly
    - Added shellcheck disable comment for intentional word splitting

8. Spinner Animation:
    - Created a spinner() function that displays a spinning animation
    - Uses |/-\ characters for the spinner
    - Shows a progress indicator during image pulling and pushing
    - Captures command output to a temporary file
    - Provides error logging if image operations fail

9. Enhanced Error Handling:
    - Improved error capturing during image pull and push operations
    - Added more robust temporary file handling
    - Maintained the existing error trapping and logging mechanisms

Some Features are pending testing.

2024-12-03 04:08 UTC, Shubhamag12 requested changes
Let us add the functionality to pull and push charts as well.
Also we should ask customers if they want us to create repositories, since we have a strict naming and if they a miss a letter or two, the EMP might fail.

2024-12-03 04:08 UTC, Shubhamag12 commented on emp/custom-registry/emp_image_helper.sh
> +            $CNT_CMD pull "$img" 2>&1
we should add `--platform linux/amd64` in this command. This is due to the fact that while pulling docker images, the docker pulls the images according to the underlying architecture and as a result the pods will crash if they are of different arch., and not of linux/amd64.

2024-12-05 06:50 UTC, Sven27 commented
To test these are the formats  
(for ecr)
./emp_image_helper.sh push public.ecr.aws/o5r0j4u8 --type ecr --profile emp-dev-admin --region us-east-1
(for jfrog)
./cred.sh push artifactory.platform9.horse --type jfrog --creds ZW1wLWF1dG9tYXRpb246S2Y5UVJiKkRwTUVG --port 443
The cred need to be base64 encoded

2024-12-05 08:14 UTC, sharma-tapas reviewed
Instead of calling out JFrog just say registry.

2024-12-05 08:14 UTC, sharma-tapas commented on emp/custom-registry/emp_image_helper.sh
> +                        echo "AWS Profile: $profile"  # Debugging
use debug instead of echo for debug logs

2024-12-14 14:47 UTC, maheshbaviskar commented on emp/custom-registry/emp_image_helper.sh
> +		        debug "tagging:$tg"
Remove this line as this this gives error $tg before assign or move tag code above this condition.

2024-12-18 09:03 UTC, Sven27 commented
test images
![Screenshot 2024-12-18 at 2 08 24 PM](https://github.com/user-attachments/assets/1e5d1dc0-5820-49bc-a5db-6dd955bb4b9b)

2024-12-23 07:04 UTC, Sven27 commented
![Uploading Screenshot 2024-12-23 at 12.33.58 PM.png…]()

2024-12-23 07:15 UTC, Sven27 commented
<img width="1111" alt="Screenshot 2024-12-23 at 12 33 58 PM" src="https://github.com/user-attachments/assets/681c8f9a-4281-4152-b9ac-d3ab10a751e3" />

2024-12-23 08:43 UTC, AnirudhPokala approved these changes

2024-12-23 10:18 UTC, Sven27 approved these changes

2024-12-23 11:40 UTC, merged